Repository Monday-Morning/project-tahiti, pull requests merged in 2022-08, with the labels that each got.

#247 docs: add reclamation link
  README.md
Labels: documentation

#246 style: use default container width
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/Footer.js
  client/src/components/marginals/TopBar.js
  client/src/components/portfolio/UserCard.js
  client/src/components/portfolio/Works.js
  client/src/config/ApolloClient.js
  client/src/screens/About.js
  client/src/screens/Article.js
  client/src/screens/Category.js
  client/src/screens/Contact.js
  client/src/screens/Expressions.js
  client/src/screens/Guide.js
  client/src/screens/Home.js
  client/src/screens/Live.js
  client/src/screens/Podcast.js
  client/src/screens/Policy.js
  client/src/screens/SearchPage.jsx
Labels: enhancement

#240 feat: replace old portfolio
  client/src/config/ApolloClient.js
  client/src/graphql/queries/user/getUserById.js
  client/src/graphql/queries/user/getUserByOldUserName.js
  client/src/pages/portfolio/[...userId].jsx
  client/src/pages/portfolio/[userId]/[name].jsx
  client/src/utils/getUserSlug.js
Labels: enhancement, wip, bugfix

#244 feat: user onboarding
  client/package.json
  client/src/assets/placeholder/onboarding.js
  client/src/components/onboarding/stages/Welcome.js
  client/src/config/ApolloClient.js
  client/src/config/firebase.js
  client/src/context/auth/AuthContext.js
  client/src/context/auth/AuthState.js
  client/src/pages/_app.jsx
  client/src/pages/admin/index.jsx
  client/src/pages/onboarding.jsx
  client/src/screens/Onboarding.js
  client/yarn.lock
Labels: enhancement, wip

#233 feat: add expression and expression subcategory page
  client/src/components/expressions/FeatureArticle.js
  client/src/components/expressions/Section.js
  client/src/components/expressions/SmallCard.js
  client/src/pages/expressions/[subCategory].jsx
  client/src/pages/expressions/index.jsx
  client/src/pages/expressions/podcasts.jsx
  client/src/screens/Expressions.js
  client/src/utils/getRoutes.js
Labels: enhancement, wip

#250 style: use default container width in subcategory
  client/src/screens/SubCategory.js
Labels: bugfix
