Repository Monday-Morning/project-tahiti, pull requests merged in 2022-10, with the labels that each got.

#273 style: fix expressions and article card width
  client/src/components/widgets/article/ArticleCardStack.js
  client/src/screens/Expressions.js
Labels: enhancement, bugfix, hacktoberfest

#265 fix: cursor pointer issue
  client/src/components/article/Header.js
  client/src/components/article/SidePanel.js
  client/src/components/categories/SectionTitle.js
  client/src/components/marginals/Footer.js
  client/src/components/podcast/BackLink.js
  client/src/components/portfolio/UserCard.js
  client/src/components/widgets/Title.js
  client/src/components/widgets/article/BigArticleCard.js
Labels: enhancement, good first issue, bugfix, hacktoberfest

#266 Fix(styles): CSS issue in contact us
  client/src/components/contact/Details.js
  client/src/components/contact/Feedback.js
Labels: bugfix, hacktoberfest

#261 feat: user onboarding
  client/package.json
  client/src/context/auth/AuthState.js
  client/src/graphql/mutations/user/registerUser.js
  client/yarn.lock
Labels: enhancement

#279 fix: ignore nulls in article array
  client/src/pages/portfolio/[...userId].jsx
Labels: bugfix, hacktoberfest

#288 fix: update prettier config and lint files
  client/.prettierrc
  client/package.json
  client/src/components/admin/subcomponents/AuthorCards.jsx
  client/src/components/userProfilePages/password/NewPasswd.js
  client/src/components/userProfilePages/widgets/ProfileCard.js
  client/src/components/widgets/Share.js
  client/src/components/widgets/article/ArticleCarousel.js
  client/src/pages/500.jsx
  client/src/pages/admin/post/browse.jsx
  client/src/pages/admin/post/media.jsx
  client/src/pages/article/[...article].jsx
  client/src/pages/index.jsx
  client/src/utils/getUserSlug.js
Labels: wip, bugfix, hacktoberfest

#259 fix : updated the terms and services content
  client/src/assets/placeholder/policy.js
  client/src/components/marginals/Footer.js
  client/src/components/policy/terms.js
  client/src/pages/policy.jsx
Labels: enhancement, safe-for-checks

#257 refactor: ui layout of addnew Page in Admin Panel
  client/src/components/admin/subcomponents/AuthorCards.jsx
  client/src/components/admin/subcomponents/CategoryCards.jsx
  client/src/components/admin/subcomponents/FeaturedMedia.jsx
  client/src/components/admin/subcomponents/sharedMedia.js
  client/src/screens/admin/AddNew.js
Labels: enhancement, wip

#278 feat: add dropdown card component
  client/src/components/widgets/DropDownCard.js
Labels: enhancement, safe-for-checks, hacktoberfest

#282 fix: firebase config error
  client/src/config/firebase.js
Labels: bugfix, safe-for-checks, hacktoberfest

#284 feat: check permission util
  client/src/utils/getAccess.js
Labels: enhancement, dependencies, safe-for-checks, hacktoberfest

#281 refactor[Admin]: change author cards
  client/src/components/admin/subcomponents/AuthorCards.jsx
  client/src/screens/admin/AddNew.js
Labels: enhancement, safe-for-checks, hacktoberfest

#291 chore(env): update env variables
  client/env/.env.sample
  client/src/config/firebase.js
  client/src/context/auth/AuthState.js
Labels: wip

#292 fix(firebase): setup config and add analytics
  client/src/config/firebase.js
  client/src/context/auth/AuthState.js
Labels: enhancement, bugfix

#293 feat: add pagination to router
  client/src/assets/placeholder/article.js
  client/src/pages/[category]/[...subCategory].jsx
  client/src/screens/Category.js
Labels: enhancement, hacktoberfest
