Repository Monday-Morning/project-tahiti, pull requests merged in 2022-05, with the labels that each got.

#193 feat(article): redirect old links to new links
  client/src/graphql/queries/article/getArticleByOldID.js
  client/src/pages/article/[...article].jsx
Labels: enhancement, safe-for-checks

#194 fix: null check for article, category and sub-category pages
  client/src/pages/[category]/[subCategory].jsx
  client/src/pages/[category]/index.jsx
  client/src/pages/article/[...article].jsx
Labels: bugfix, safe-for-checks

#189 fix(styles): squiggle text align
  client/src/components/widgets/Squiggles.js
Labels: bugfix

#196 fix(style):fix squiggle stack issue
  client/src/components/widgets/Squiggles.js
Labels: enhancement, wip, bugfix

#198 fix(style): add responsiveness to footer
  client/src/components/marginals/Footer.js
Labels: enhancement, wip, bugfix

#200 fix: add null check
  client/src/pages/[category]/[subCategory].jsx
Labels: bugfix

#206 fix: small card image not fitting properly
  client/src/components/widgets/article/SmallArticleCard.js
Labels: bugfix

#205 fix(bug): looping and filter on undefined object
  client/src/pages/[category]/[subCategory].jsx
  client/src/pages/[category]/index.jsx
Labels: bugfix
