Repository Monday-Morning/project-tahiti, pull requests merged in 2022-12, with the labels that each got.

#335 feat(footer): add go to archives section in footer
  client/src/components/marginals/Footer.js
Labels: enhancement

#340 feat(home): integrate photostory and witsdom
  client/src/components/expressions/PhotoStory.js
  client/src/components/expressions/Witsdom.js
  client/src/components/homepage/Banner.js
  client/src/pages/index.jsx
  client/src/screens/Home.js
Labels: enhancement

#337 feat: add student pulse
  client/package.json
  client/src/components/homepage/PieChart.js
  client/src/components/widgets/Pulse.js
  client/yarn.lock
Labels: enhancement

#347 fix: font family and search result condition
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/MobileNavbar.js
Labels: enhancement, bugfix

#333 feat: show all articles of latest issue
  client/src/pages/500.jsx
  client/src/screens/Home.js
Labels: enhancement, bugfix

#317 feat: auto complete suggestions on search bar
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/MobileNavbar.js
  client/src/graphql/queries/article/getAutoComplete.js
  client/src/hooks/useAutoComplete.js
Labels: enhancement

#346 fix(docs): fix links used in images of readme file
  README.md
Labels: documentation, enhancement, bugfix

#343 feat(home): integrate youtube data api to fetch video meta data from a playlist
  client/env/.env.sample
  client/package.json
  client/src/components/homepage/SocialMedia.js
  client/src/pages/index.jsx
  client/src/screens/Home.js
Labels: enhancement

#351 fix: photostory
  client/src/screens/Home.js
Labels: bugfix

#350 fix(article): remove uneven spaces in article paragraph
  client/src/components/article/Content.js
  client/src/components/article/Disclaimer.js
Labels: enhancement

#352 feat(expressions): add Photostory in Expressions Page
  client/src/components/expressions/SmallCard.js
  client/src/components/widgets/article/ArticleGrid.js
  client/src/components/widgets/article/BigArticleCard.js
  client/src/components/widgets/article/RegularArticleCard.js
  client/src/components/widgets/article/SmallArticleCard.js
  client/src/pages/expressions/index.jsx
  client/src/screens/Expressions.js
  client/src/utils/getRoutes.js
Labels: enhancement, wip

#296 feat: sac and clubs info page
  client/src/assets/placeholder/sac.js
  client/src/components/guide/Options.js
  client/src/components/widgets/ClubCards.js
  client/src/components/widgets/ClubInfoNavbar.js
  client/src/components/widgets/DropDownCard.js
  client/src/components/widgets/PostHolder.js
  client/src/components/widgets/SacInfoNavbar.js
  client/src/components/widgets/SocietyCards.js
  client/src/components/widgets/SubCategory.js
  client/src/pages/sac.jsx
  client/src/screens/Guide.js
  client/src/screens/Sac.js
Labels: enhancement

#358 feat(subcategory): add department routing
  client/src/pages/[category]/[...subCategory].jsx
  client/src/screens/SubCategory.js
  client/src/utils/getLinks.js
  client/src/utils/getRoutes.js
Labels: enhancement

#330 feat: add admin panel
  client/src/components/admin_v2/AddNew/AuthorCards.jsx
  client/src/components/admin_v2/AddNew/CategoryCard.jsx
  client/src/components/admin_v2/Browse/ArticleStatusMenu.jsx
  client/src/components/admin_v2/Browse/DialogBox.jsx
  client/src/components/admin_v2/Common/FeaturedMedia.jsx
  client/src/components/admin_v2/Common/SnackBarAleart.jsx
  client/src/components/admin_v2/Common/Tags.jsx
  client/src/components/admin_v2/Common/sharedMedia.js
  client/src/components/admin_v2/Marginals/Content.js
  client/src/components/admin_v2/Marginals/Header.js
  client/src/components/admin_v2/Marginals/Marginals.js
  client/src/components/admin_v2/Marginals/Navigator.js
  client/src/context/auth/AuthState.js
  client/src/graphql/mutations/article/createArticle.js
  client/src/graphql/mutations/article/updateArticleApprovalStatus.js
  client/src/graphql/mutations/article/updateArticleCategories.js
  client/src/graphql/mutations/article/updateArticleCover.js
  client/src/graphql/mutations/article/updateArticleProps.js
  client/src/graphql/mutations/article/updateArticlePublishStatus.js
  client/src/graphql/mutations/article/updateArticleRestriction.js
  client/src/graphql/mutations/article/updateArticleUsers.js
  client/src/graphql/mutations/media/addMedia.js
  client/src/graphql/queries/article/countTotalArticles.js
  client/src/graphql/queries/article/getRestrictedArticleData.js
  client/src/graphql/queries/article/listAllArticles.js
  client/src/graphql/queries/user/listAllUser.js
  client/src/pages/admin_v2/addnew.jsx
  client/src/pages/admin_v2/browse.jsx
  client/src/pages/admin_v2/edit/[id].jsx
  client/src/pages/admin_v2/index.jsx
  client/src/pages/admin_v2/media.jsx
  client/src/screens/admin_v2/AddNew.jsx
  client/src/screens/admin_v2/Browse.jsx
  client/src/screens/admin_v2/Edit.jsx
  client/src/screens/admin_v2/Media.jsx
  client/src/utils/categoryCard.js
  client/src/utils/getAccess.js
  client/src/utils/imageKit.js
  client/yarn.lock
Labels: enhancement

#356 feat: get podcast data
  client/src/pages/expressions/index.jsx
  client/src/utils/getSpotifyAccessToken.js
Labels: enhancement

#359 chore: fix prettier issue
  client/src/components/widgets/ClubInfoNavbar.js
Labels: good first issue

#364 feat: enable dynamic spotify embed
  client/src/components/podcast/List.js
  client/src/pages/expressions/index.jsx
  client/src/screens/Expressions.js
  client/src/utils/getLinks.js
  client/src/utils/getRoutes.js
Labels: enhancement, wip

#384 feat: basic integration of live page
  client/src/assets/placeholder/live.js
  client/src/components/live/companyBanner.js
  client/src/components/live/courseSelector.js
  client/src/components/live/liveData.js
  client/src/components/live/nameFilter.js
  client/src/graphql/queries/live/getLiveByYearAndSemester.js
  client/src/pages/live.jsx
  client/src/screens/Live.js
Labels: wip
