Repository Monday-Morning/project-tahiti, pull requests merged in 2022-11, with the labels that each got.

#280 feat: add article table
  client/src/components/article/ArticleTable.js
  client/src/components/article/Content.js
Labels: enhancement, hacktoberfest

#298 feat(guide): create Health and Emergency Info page
  client/src/assets/placeholder/healthAndEmergencyInfo.js
  client/src/components/healthAndEmergencyInfo/Info.js
  client/src/components/widgets/DropDownCard.js
  client/src/pages/healthAndEmergencyInfo.jsx
  client/src/screens/HealthAndEmergency.js
Labels: enhancement

#299 fix: remove replaceall from table
  client/src/components/article/ArticleTable.js
Labels: bugfix

#294 chore: change profile pic store path
  client/src/context/auth/AuthState.js
Labels: bugfix, hacktoberfest

#300 fix: table first cell
  client/src/components/article/ArticleTable.js
Labels: bugfix

#303 feat: setup firebase emulator
  .firebaserc
  client/src/config/ApolloClient.js
  client/src/config/firebase.js
  client/src/context/auth/AuthState.js
  firebase.json
Labels: enhancement

#306 feat(graphql): archive page integration
  client/src/components/guide/calendar.js
  client/src/graphql/queries/article/listArticleByYearAndMonth.js
  client/src/pages/archive/[...yearAndMonth].jsx
  client/src/screens/Archive.jsx
Labels: enhancement

#302 wip(healthInfo): content update
  client/src/assets/images/healthAndEmergencyInfo/cws.png
  client/src/assets/images/healthAndEmergencyInfo/health.png
  client/src/assets/placeholder/healthInfo.js
  client/src/components/guide/Options.js
  client/src/components/healthAndEmergencyInfo/Info.js
  client/src/components/healthInfo/Info.js
  client/src/pages/info/health.jsx
  client/src/screens/HealthInfo.js
Labels: enhancement, wip

#309 feat(expressions): add page base routing
  client/src/pages/expressions/[...subCategory].jsx
  client/src/screens/Expressions.js
Labels: enhancement, safe-for-checks

#315 docs: add nextjs in readme
  README.md
Labels: documentation

#316 feat: autocomplete for search bar
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/MobileNavbar.js
  client/src/graphql/queries/article/getAutoComplete.js
  client/src/hooks/useAutoComplete.js
Labels: enhancement

#310 fix(article): add null check for authorName
  client/src/components/article/Header.js
Labels: enhancement, bugfix
