Repository Monday-Morning/project-tahiti, pull requests merged in 2022-06, with the labels that each got.

#216 fix: positioning issue of scroll button
  client/src/components/shared/button/ScrollToTopButton.js
Labels: wip, bugfix, safe-for-checks

#215 style: change cursor type to pointer of article cards
  client/src/components/widgets/article/RegularArticleCard.js
  client/src/components/widgets/article/SmallArticleCard.js
Labels: wip, bugfix, safe-for-checks

#218 feat: add portfolio page
  client/src/components/portfolio/Backlink.js
  client/src/components/portfolio/UserCard.js
  client/src/components/portfolio/Works.js
  client/src/components/shared/MarkdownWrapper.js
  client/src/components/widgets/article/RegularArticleCard.js
  client/src/graphql/fragments/article/basicArticleData.js
  client/src/graphql/queries/article/getListOfArticles.js
  client/src/graphql/queries/user/getUserById.js
  client/src/pages/portfolio/[userId]/[name].jsx
  client/src/screens/Portfolio.js
Labels: enhancement, wip, bugfix, safe-for-checks

#221 fix: cwc subcategory name change
  client/src/utils/getRoutes.js
Labels: safe-for-checks

#223 chore: upgrade react 17 to 18
  client/package.json
  client/yarn.lock
Labels: dependencies

#227 fix: variable not defined error
  client/src/screens/Category.js
Labels: bugfix

#228 fix(style): max width of the app
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/Footer.js
  client/src/components/marginals/TopBar.js
  client/src/screens/About.js
  client/src/screens/Article.js
  client/src/screens/Category.js
  client/src/screens/Contact.js
  client/src/screens/Expressions.js
  client/src/screens/Guide.js
  client/src/screens/Home.js
  client/src/screens/Live.js
  client/src/screens/PhotoStory.js
  client/src/screens/Podcast.js
  client/src/screens/Policy.js
  client/src/screens/SearchPage.jsx
  client/src/screens/SubCategory.js
  client/src/screens/UserProfile.js
Labels: bugfix

#232 fix: author image and sidebar overlap issue
  client/src/components/article/Header.js
Labels: bugfix

#231 fix: author id issue in small article card
  client/src/components/widgets/article/SmallArticleCard.js
Labels: bugfix

#230 fix(style): fix website max width issue
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/Footer.js
  client/src/components/marginals/TopBar.js
  client/src/components/portfolio/UserCard.js
  client/src/components/portfolio/Works.js
  client/src/screens/About.js
  client/src/screens/Article.js
  client/src/screens/Category.js
  client/src/screens/Contact.js
  client/src/screens/Expressions.js
  client/src/screens/Guide.js
  client/src/screens/Home.js
  client/src/screens/Live.js
  client/src/screens/PhotoStory.js
  client/src/screens/Podcast.js
  client/src/screens/Policy.js
  client/src/screens/SearchPage.jsx
  client/src/screens/SubCategory.js
  client/src/screens/UserProfile.js
Labels: bugfix
