Repository Monday-Morning/project-tahiti, pull requests merged in 2022-07, with the labels that each got.

#234 feat: add on demand ISR for article
  client/package.json
  client/src/pages/api/revalidate.js
  client/yarn.lock
Labels: enhancement

#237 fix: blur issue in activity indicator
  client/src/components/shared/ActivityIndicator.js
Labels: enhancement, wip, bugfix

#235 feat:admin panel
  client/package.json
  client/src/components/admin/Header.jsx
  client/src/components/admin/Sidebar/Sidebar.jsx
  client/src/components/admin/Sidebar/menulist/Menulist.jsx
  client/src/components/admin/Sidebar/menulist/NavCollapse.jsx
  client/src/components/admin/Sidebar/menulist/NavGroup.jsx
  client/src/components/admin/Sidebar/menulist/NavItem.jsx
  client/src/components/admin/subcomponents/AuthorCards.jsx
  client/src/components/admin/subcomponents/CategoryCards.jsx
  client/src/components/admin/subcomponents/FeaturedMedia.jsx
  client/src/components/admin/subcomponents/PublishCards.jsx
  client/src/components/admin/subcomponents/sharedMedia.js
  client/src/context/SidebarContext.jsx
  client/src/pages/_app.jsx
  client/src/pages/admin/index.jsx
  client/src/pages/admin/post/add-new.jsx
  client/src/pages/admin/post/browse.jsx
  client/src/pages/admin/post/media.jsx
  client/src/screens/admin/AddNew.js
  client/src/screens/admin/Admin.js
  client/src/screens/admin/Browse.js
  client/src/screens/admin/Media.js
  client/src/utils/getAdminRoutes.js
  client/yarn.lock
Labels: enhancement, wip, safe-for-checks

#238 fix: categories department tags issues
  client/src/utils/determineCategory.js
Labels: bug, bugfix, safe-for-checks

#241 fix: get noofarticle by articlelist
  client/src/pages/portfolio/[userId]/[name].jsx
Labels: bugfix
