Repository Monday-Morning/project-tahiti, pull requests merged in 2023-01, with the labels that each got.

#391 fix: redirect live page to comingsoon
  client/src/pages/live.jsx
Labels: bugfix

#338 feat(events): add calendar component for events page
  client/package.json
  client/src/components/calendar/EventCalendar.js
  client/src/components/calendar/NewEvent.js
  client/yarn.lock
Labels: enhancement, help wanted, question

#387 fix: live and department links
  client/src/components/widgets/SubCategoryLink.js
  client/src/screens/Category.js
  client/src/screens/SubCategory.js
Labels: bugfix

#373 fix: autocomplete search-bar flickering
  client/src/components/marginals/DesktopNavbar.js
  client/src/hooks/useAutoComplete.js
Labels: enhancement, bugfix

#375 fix: article overflow due to link
  client/src/components/article/Content.js
Labels: bugfix

#370 fix: add null check for article
  client/src/screens/Home.js
Labels: enhancement, bugfix

#388 feat: add onboarding pagination
  client/src/assets/placeholder/onboarding.js
  client/src/components/onboarding/Pagination.js
  client/src/components/onboarding/pagination.js
  client/src/components/onboarding/stages/NewsletterSignup.js
  client/src/components/onboarding/stages/SelectTopics.js
  client/src/components/onboarding/stages/VerifyEmail.js
  client/src/components/onboarding/stages/Welcome.js
  client/src/screens/Onboarding.js
Labels: enhancement, bugfix

#386 fix: set placed data in mobile screen
  client/src/components/live/companyBanner.js
  client/src/components/live/courseSelector.js
  client/src/components/live/liveData.js
  client/src/components/live/nameFilter.js
  client/src/components/live/typeSelector.js
  client/src/screens/Live.js
Labels: enhancement

#368 fix(article): fix table data and max width of article
  client/src/components/article/ArticleTable.js
  client/src/components/article/Tags.js
  client/src/screens/Article.js
Labels: enhancement, bugfix

#396 fix: handle null contributions
  client/src/components/portfolio/UserCard.js
  client/src/components/portfolio/Works.js
  client/src/pages/portfolio/[...userId].jsx
Labels: bugfix

#385 fix: alignment of table of content
  client/src/components/article/TableOfContent.js
Labels: enhancement

#403 feat: add dark theme context
  client/src/components/marginals/TopBar.js
  client/src/components/widgets/ToggleModeIcon.js
  client/src/config/themes/dark.js
  client/src/context/ThemeContext.jsx
  client/src/pages/_app.jsx
Labels: enhancement

#408 feat: remove cwc section
  client/src/components/marginals/DesktopNavbar.js
  client/src/utils/getRoutes.js
Labels: enhancement

#409 fix: add sac posts
  client/src/components/guide/Options.js
  client/src/components/widgets/PostHolder.js
  client/src/components/widgets/SacInfoNavbar.js
  client/src/components/widgets/SocietyCards.js
  client/src/screens/Sac.js
Labels: enhancement
