Repository Monday-Morning/project-tahiti, pull requests merged in 2023-02, with the labels that each got.

#410 chore: remove url hardcoding
  client/src/config/ApolloClient.js
  client/src/context/auth/AuthState.js
  client/src/utils/getAccess.js
  client/src/utils/getSpotifyAccessToken.js
Labels: wip

#400 fix: og tags of portfolio
  client/src/pages/portfolio/[...userId].jsx
Labels: enhancement, bugfix

#415 feat(theme): add color codes to dark theme
  client/src/components/homepage/Banner.js
  client/src/components/homepage/Trending.js
  client/src/components/marginals/Footer.js
  client/src/components/shared/TitleWrapper.js
  client/src/components/widgets/Squiggles.js
  client/src/components/widgets/SubCategory.js
  client/src/components/widgets/SubCategoryLink.js
  client/src/components/widgets/article/ArticleCarousel.js
  client/src/components/widgets/article/BigArticleCard.js
  client/src/components/widgets/article/RegularArticleCard.js
  client/src/components/widgets/article/SmallArticleCard.js
  client/src/config/themes/dark.js
  client/src/config/themes/light.js
Labels: enhancement

#405 feat: integrate tags in admin panel
  client/src/components/admin_v2/Common/FeaturedMedia.jsx
  client/src/components/admin_v2/Common/Tags.jsx
  client/src/graphql/mutations/article/updateArticleTags.js
  client/src/graphql/mutations/tag/createTag.js
  client/src/graphql/queries/article/listAllArticles.js
  client/src/graphql/queries/tag/getTagAutocomplete.js
  client/src/hooks/useTagAutoComplete.js
  client/src/pages/admin_v2/browse.jsx
  client/src/pages/admin_v2/index.jsx
  client/src/screens/admin_v2/Browse.jsx
  client/src/screens/admin_v2/Edit.jsx
Labels: enhancement, bugfix

#401 feat: add hall page
  client/src/assets/images/halls/cvr.jpg
  client/src/assets/images/halls/dba.jpg
  client/src/assets/images/halls/gdb.jpg
  client/src/assets/images/halls/hb.jpg
  client/src/assets/images/halls/kms.jpg
  client/src/assets/images/halls/mss.jpg
  client/src/assets/images/halls/mv.jpg
  client/src/assets/images/halls/sd.jpg
  client/src/assets/images/halls/vs.jpg
  client/src/assets/placeholder/hallInfo.js
  client/src/components/guide/Options.js
  client/src/components/hallInfo/Info.js
  client/src/components/widgets/DropDownCard.js
  client/src/pages/hallInfo.jsx
  client/src/screens/HallInfo.js
Labels: enhancement

#420 fix(guide): add icon3 in option.js
  client/src/components/guide/Options.js
Labels: bugfix

#411 fix: auth key errors
  client/src/config/ApolloClient.js
  client/src/context/auth/AuthState.js
Labels: bugfix

#421 bug(theme): conflicting touch pad area
  client/src/components/marginals/MobileNavbar.js
Labels: bug

#423 chore: upgrade packages to latest minor-patch
  client/yarn.lock
Labels: dependencies

#424 feat(theme): replace hard coded colors
  client/src/components/contact/Details.js
  client/src/components/contact/Feedback.js
  client/src/components/guide/Carousel.js
  client/src/components/guide/Options.js
  client/src/components/photostory/Carousel.js
  client/src/components/shared/button/BackButton.js
  client/src/components/widgets/BigCarousel.js
  client/src/components/widgets/article/ArticleGrid.js
Labels: enhancement

#427 feat(theme): add logo
  client/public/index.css
  client/src/assets/images/logos/logo_full_white.png
  client/src/assets/images/logos/logo_white.png
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/Footer.js
  client/src/components/marginals/MobileNavbar.js
  client/src/components/widgets/SubCategory.js
  client/src/components/widgets/SubCategoryLink.js
  client/src/context/ThemeContext.jsx
Labels: enhancement

#422 feat(admin): user info update form ui
  client/src/components/admin_v2/Marginals/Form.js
Labels: enhancement
