Repository Monday-Morning/project-tahiti, pull requests merged in 2023-09, with the labels that each got.

#468 refactor: admin graphql client and auth
  client/src/components/admin_v2/Common/FeaturedMedia.jsx
  client/src/components/admin_v2/Common/Tags.jsx
  client/src/components/admin_v2/Marginals/Header.js
  client/src/components/admin_v2/issues/IssueDialogBox.jsx
  client/src/hooks/useAutoComplete.js
  client/src/hooks/useTagAutoComplete.js
  client/src/pages/admin_v2/addnew.jsx
  client/src/pages/admin_v2/browse.jsx
  client/src/pages/admin_v2/issues/index.jsx
  client/src/screens/admin_v2/AddNew.jsx
  client/src/screens/admin_v2/Browse.jsx
  client/src/screens/admin_v2/Edit.jsx
  client/src/screens/admin_v2/Issues.jsx
  client/src/utils/getAccess.js
Labels: enhancement

#469 fix: missing pagination component
  client/src/components/onboarding/Pagination.js
Labels: bugfix

#467 chore: update sac info page
  client/src/components/widgets/SacInfoNavbar.js
Labels: documentation

#460 fix: search bar
  client/src/components/marginals/DesktopNavbar.js
  client/src/components/marginals/MobileNavbar.js
Labels: enhancement
