Repository Monday-Morning/project-tahiti, pull requests merged in 2023-03, with the labels that each got.

#426 chore: user onboarding flow
  client/src/assets/placeholder/onboarding.js
  client/src/components/onboarding/stages/NewsletterSignup.js
  client/src/components/onboarding/stages/SelectTopics.js
  client/src/components/onboarding/stages/VerifyEmail.js
  client/src/components/onboarding/stages/Welcome.js
  client/src/context/auth/AuthState.js
  client/src/graphql/mutations/user/newsLetterSubscription.js
  client/src/graphql/mutations/user/updateUserProfilePicture.js
  client/src/graphql/mutations/user/updateUserTopics.js
  client/src/graphql/queries/user/getFirebaseUserByEmail.js
Labels: enhancement, wip

#440 feat: webmail authentication userflow
  client/src/assets/placeholder/onboarding.js
  client/src/components/onboarding/stages/NewsletterSignup.js
  client/src/components/onboarding/stages/SelectTopics.js
  client/src/components/onboarding/stages/VerifyEmail.js
  client/src/components/onboarding/stages/Welcome.js
  client/src/config/ApolloClient.js
  client/src/config/imagekit.js
  client/src/context/auth/AuthState.js
  client/src/graphql/mutations/user/addNITRMail.js
  client/src/graphql/mutations/user/registerUser.js
  client/src/graphql/mutations/user/updateUserProfilePicture.js
  client/src/graphql/mutations/user/updateUserTopics.js
  client/src/screens/Onboarding.js
  client/src/utils/getAccess.js
Labels: enhancement

#439 fix: darktheme styling issues
  client/src/components/categories/SectionTitle.js
  client/src/components/widgets/article/ArticleCarousel.js
Labels: bugfix

#441 feat: user onboarding experience
  client/src/components/onboarding/stages/VerifyEmail.js
  client/src/components/onboarding/stages/Welcome.js
  client/src/context/auth/AuthState.js
  client/src/graphql/queries/user/checkNITRMail.js
  client/src/screens/Onboarding.js
Labels: enhancement
