Repository Monday-Morning/project-tahiti, pull requests merged in 2023-07, with the labels that each got.

#453 feat(home): increase number of displayed articles on the home page
  client/src/pages/index.jsx
  client/src/screens/Home.js
Labels: enhancement

#455 chore: delete repo docs
  client/public/template.html
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/blog/2019-05-28-hola.md
  docs/blog/2019-05-29-hello-world.md
  docs/blog/2019-05-30-welcome.md
  docs/docs/mdx.md
  docs/docs/newsletter.md
  docs/docs/onboarding.md
  docs/docs/selectTopics.md
  docs/docs/verifyEmail.md
  docs/docs/welcome.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/static/.nojekyll
  docs/static/img/favicon.ico
  docs/static/img/logo.png
  docs/static/img/logo.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/yarn.lock
Labels: documentation

#456 fix(home): remove duplicate article in home page
  client/src/screens/Home.js
Labels: bugfix

#444 fix(photostory): optimise the state update in photostory
  client/src/components/photostory/Carousel.js
Labels: enhancement, bugfix
